<?php
/**
 * Vaimo Brand
 *
 * @author Andrii Vivcharyk <andrii.vivcharyk@vaimo.com>
 * @package Vaimo_Brand
 * @copyright Copyright (c) 2021 Vaimo (http://www.vaimo.com)
 */
/**
 * @var $block Vaimo\Brand\Block\Brand
 */
$collection = $block->getBrands();
?>
<div class="container">
    <div class="row">
        <h1>Brand List</h1>
    </div>
    <?php foreach ($collection as $item): ?>
        <div class="row">
            <a href="http://andreyviv.test/brand/single/view/id/<?= $item->getId(); ?>">
                <img src="<?= $item->getImageLink(); ?>"
                     width="150"
                     height="150"
                     alt="<?= $item->getName(); ?>">
                <div>
                    <h3><?= $item->getName(); ?></h3>
                    <p><?= $item->getDescription(); ?></p>
                </div>
            </a>
        </div>
    <?php endforeach; ?>
</div>
