<?php
/**
 * Vaimo Brand
 *
 * @author Andrii Vivcharyk <andrii.vivcharyk@vaimo.com>
 * @package Vaimo_Brand
 * @copyright Copyright (c) 2021 Vaimo (http://www.vaimo.com)
 */
/**
 * @var $block Vaimo\Brand\Block\Test
 */
?>
<script type="text/x-magento-init">
    {
        "#test-element": {
            "Vaimo_Brand/js/fortest": <?= $block->getJsLayout(); ?>
        }
    }

</script>
<div id="test-element">
    <p><?= $block->escapeHtml(__('Script test!')) ?></p>
</div>

